ignore:
  - GHSA-248v-346w-9cwc
  - GHSA-6c3j-c64m-qhgq
  - GHSA-9mvj-f7w8-pvh2
  - GHSA-g92j-qhmh-64v2
  - GHSA-gxr4-xjj5-5px2
  - GHSA-jpcq-cgw6-v4j6
  - GHSA-rmxg-73gg-4p98
  - GHSA-248v-346w-9cwc # Certifi removes GLOBALTRUST root certificate (https://github.com/advisories/GHSA-248v-346w-9cwc)
  - GHSA-g92j-qhmh-64v2 # Sentry's Python SDK unintentionally exposes environment variables to subprocesses (https://github.com/advisories/GHSA-g92j-qhmh-64v2)
  - GHSA-9mvj-f7w8-pvh2 # Bootstrap Cross-Site Scripting (XSS) vulnerability (https://github.com/advisories/GHSA-9mvj-f7w8-pvh2)
  - GHSA-rrqc-c2jx-6jgv # Django allows enumeration of user e-mail addresses
  - GHSA-248v-346w-9cwc # Certifi removes GLOBALTRUST root certificate (https://github.com/advisories/GHSA-248v-346w-9cwc)
  - GHSA-rrqc-c2jx-6jgv # Django allows enumeration of user e-mail addresses (https://github.com/advisories/GHSA-rrqc-c2jx-6jgv)
  - GHSA-g92j-qhmh-64v2 # Sentry's Python SDK unintentionally exposes environment variables to subprocesses (https://github.com/advisories/GHSA-g92j-qhmh-64v2)

