# Generated by Django 3.2.24 on 2024-02-15 02:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('video', '0004_glossvideo_video_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossVideoToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            to='video.glossvideo')),
            ],
        ),
    ]
