# Generated by Django 2.2.11 on 2022-05-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_gloss_filmbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='sn',
            field=models.IntegerField(blank=True, help_text='Sign Number must be a unique integer and defines the ordering of signs in the dictionary', null=True, unique=True, verbose_name='Sign Number'),
        ),
    ]
