# Generated by Django 2.2.11 on 2022-05-12 01:34

from django.db import migrations, models
import signbank.dictionary.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_gloss_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='sn',
            field=models.IntegerField(blank=True, default=signbank.dictionary.models.from_8000, help_text='Sign Number must be a unique integer and defines the ordering of signs in the dictionary', null=True, unique=True, verbose_name='Sign Number'),
        ),
    ]
