# Generated by Django 2.2.11 on 2022-05-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_auto_20220512_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='videoexample1',
            field=models.CharField(
                blank=True, help_text='Annotated translation for video example 1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gloss',
            name='videoexample1_translation',
            field=models.CharField(
                blank=True, help_text='Natural language translation for video example 1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gloss',
            name='videoexample2',
            field=models.CharField(
                blank=True, help_text='Annotated translation for video example 2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gloss',
            name='videoexample2_translation',
            field=models.CharField(
                blank=True, help_text='Natural language translation for video example 2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gloss',
            name='videoexample3',
            field=models.CharField(
                blank=True, help_text='Annotated translation for video example 3', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gloss',
            name='videoexample3_translation',
            field=models.CharField(
                blank=True, help_text='Natural language translation for video example 3', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gloss',
            name='videoexample4',
            field=models.CharField(
                blank=True, help_text='Annotated translation for video example 4', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gloss',
            name='videoexample4_translation',
            field=models.CharField(
                blank=True, help_text='Natural language translation for video example 4', max_length=255, null=True),
        )
    ]
