# Generated by Django 2.2.11 on 2022-05-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0015_merge_20220525_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloss',
            name='concise',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, help_text='Included in print 2002 Concise Dictionary of NZSL', verbose_name='Concise'),
        ),
    ]
