# Generated by Django 3.2.13 on 2022-06-23 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0034_merge_20220623_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='lemma',
            field=models.ForeignKey(blank=True, db_column='lemma', limit_choices_to={'field': 'lemma'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lemma', to='dictionary.fieldchoice', to_field='machine_value', verbose_name='Lemma'),
        ),
    ]
