# Generated by Django 3.2.23 on 2024-01-09 05:58
from django.contrib.auth import get_user_model
from django.db import migrations

User = get_user_model()


def get_or_create_tag(apps, schema_validation):
    TagModel = apps.get_model("tagging", "Tag")
    TagModel.objects.get_or_create(name="nzsl-share")


def create_share_import_user(apps, schema_validation):
    User.objects.create(
        username="nzsl_share_importer",
        first_name="Importer",
        last_name="NZSL Share",
        email="dummy@email.com",
        is_staff=True,
        is_active=True
    )


def delete_nzsl_share_importer(apps, schema_validation):
    User.objects.filter(
        username="nzsl_share_importer",
        first_name="Importer",
        last_name="NZSL Share",
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0042_new_video_type_choices"),
        ("video", "0004_glossvideo_video_type"),
        ('tagging', '0003_adapt_max_tag_length'),
    ]

    operations = [
        migrations.RunPython(create_share_import_user, reverse_code=delete_nzsl_share_importer),
        migrations.RunPython(get_or_create_tag, reverse_code=migrations.RunPython.noop)
    ]
