# Generated by Django 3.2.23 on 2024-01-24 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0044_share_validation_aggregtion_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_seen', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not sure', 'Not sure')], help_text="Result of the survey question 'Have seen it or use it myself'", max_length=50)),
                ('response_id', models.CharField(help_text='Identifier of specific survey result in Qualitrics', max_length=255)),
                ('respondent_first_name', models.CharField(help_text='Survey respondents first name', max_length=255, null=True)),
                ('respondent_last_name', models.CharField(help_text='Survey respondents last name', max_length=255, null=True)),
                ('respondent_email', models.EmailField(help_text='Survey respondents email', max_length=254, null=True, blank=True)),
                ('comment', models.TextField(help_text='Optional comment the survey respondent can leave about the gloss', null=True)),
                ('contact_with_nzsl_requested', models.BooleanField(default=False, help_text='Boolean value that indicates if the survey respondent would like to be contacted by NZSL to discuss the gloss further')),
                ('gloss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_records', to='dictionary.gloss')),
            ],
        ),
    ]
