# Generated by Django 3.2.23 on 2024-02-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0045_validation_record_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationrecord',
            name='contact_with_nzsl_requested',
        ),
        migrations.RemoveField(
            model_name='validationrecord',
            name='respondent_email',
        ),
        migrations.AlterField(
            model_name='validationrecord',
            name='response_id',
            field=models.CharField(help_text='Identifier of specific survey result in Qualtrics', max_length=255),
        ),
    ]
