# Generated by Django 3.2.24 on 2024-02-20 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0047_unique_together_for_validation_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualValidationAggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='', help_text='The group the manual validation round was conducted for', max_length=255)),
                ('sign_seen_yes', models.PositiveIntegerField()),
                ('sign_seen_no', models.PositiveIntegerField()),
                ('sign_seen_not_sure', models.PositiveIntegerField()),
                ('comments', models.TextField(blank=True, default='', help_text='Optional comments made about the gloss during manual validation')),
                ('gloss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_validation_aggregation', to='dictionary.gloss')),
            ],
        ),
    ]
