# Generated by Django 3.2.24 on 2024-02-22 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0048_manual_validation_aggregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gloss',
            name='nzsl_share_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gloss',
            name='lemma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionary.lemma', verbose_name='Lemma'),
        ),
    ]
