# Generated by Django 3.2.25 on 2025-02-04 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0049_alter_gloss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldchoice',
            options={'ordering': ['field', 'english_name'], 'verbose_name': 'Field choice', 'verbose_name_plural': 'Field choices'},
        ),
    ]
